changelog:
  categories:
    - title: Breaking Changes 🚨
      labels:
        - breaking-change
    - title: Features ✨
      labels:
        - enhancement
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Documentation 📚
      labels:
        - documentation
        - docs
    - title: Maintenance 🔧
      labels:
        - maintenance
        - dependencies
        - Renovate
