changelog:
  categories:
    - title: Breaking Changes 🚨
      labels:
        - breaking-change
        - Semver Major
    - title: Features ✨
      labels:
        - feature
        - Enhancement
        - enhancement
        - Semver Minor
    - title: Bug Fixes 🐛
      labels:
        - Bug
        - bug
        - Hotfix
    - title: Documentation 📚
      labels:
        - Documentation
        - documentation
        - docs
    - title: Maintenance 🔧
      labels:
        - maintenance
        - dependencies
        - Chore
        - GitHub Actions
        - Renovate
        - Semver Patch
